# Generated by Django 4.2 on 2023-05-01 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("frontend", "0002_userlikedevent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserLikedEvent",
            new_name="LinkedEvent",
        ),
        migrations.AddField(
            model_name="event",
            name="likes_count",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="likes",
            field=models.ManyToManyField(
                related_name="linked_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
