# Generated by Django 4.2 on 2023-05-01 03:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "frontend",
            "0003_rename_userlikedevent_linkedevent_event_likes_count_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LinkedEvent",
            new_name="LikedEvent",
        ),
    ]
