# Generated by Django 4.2 on 2023-05-01 03:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0004_rename_linkedevent_likedevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="likes",
        ),
    ]
