# Generated by Django 4.2 on 2023-05-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0008_alter_event_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="likes_count",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
