# Generated by Django 4.2 on 2023-05-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0009_alter_event_likes_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="likes_count",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
